chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='chat'),
    path('<str:room_name>/', views.room, name='room'),
]

events/urls.py
from __future__ import unicode_literals
from django.urls import re_path
from . import views

urlpatterns = [
    re_path(r'^$', views.EventMonthView.as_view(), name='list'),
    re_path(r'^month/shift/$', views.EventMonthView.as_view(), name='month_shift'),
    re_path(r'^event-list/shift/$', views.EventMonthView.as_view(), name='event_list_shift'),
    re_path(r'^cal-and-list/shift/$', views.EventMonthView.as_view(), name='cal_and_list_shift'),
    re_path(r'^event/(?P<pk>[\w-]+)/$', views.EventDetailView.as_view(), name='detail'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2}|\d)/$', views.EventMonthView.as_view(), name='list'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2}|\d)/(?P<day>\d{2}|\d)/$', views.EventDayView.as_view(), name='day_list'),

]

healthmanagement/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('accounts.urls')),
    path('chat/', include('chat.urls')),
    path('events/', include(('events.urls', 'events'), namespace='calendar')),
    path('oauth/', include('social_django.urls'), name='social_auth'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/models.py
from __future__ import unicode_literals

import datetime

from django.conf import settings
from django.core.exceptions import ValidationError
from django.urls import reverse
from django.db import models

from django.utils import timezone

from django.utils.functional import cached_property
from django.utils.translation import ugettext_lazy as _

from .managers import EventManager

auth_user_model = getattr(settings, "AUTH_USER_MODEL", "auth.User")


class Event(models.Model):
    REPEAT_CHOICES = (
        ('NEVER', _('Never')),
        ('DAILY', _('Every Day')),
        ('WEEKDAY', _('Every Weekday')),
        ('WEEKLY', _('Every Week')),
        ('BIWEEKLY', _('Every 2 Weeks')),
        ('MONTHLY', _('Every Month')),
        ('YEARLY', _('Every Year')),
    )

    start_date = models.DateTimeField(verbose_name=_("start date"))
    end_date = models.DateTimeField(_("end date"))
    all_day = models.BooleanField(_("all day"), default=False)
    repeat = models.CharField(
        _("repeat"), max_length=15, choices=REPEAT_CHOICES, default='NEVER'
    )
    end_repeat = models.DateField(_("end repeat"), null=True, blank=True)
    title = models.CharField(_("title"), max_length=255)
    description = models.TextField(_("description"))
    thumbnail = models.ImageField(_("thumbnail"), upload_to="images/", blank=True)
    location = models.ManyToManyField(
        'Location', verbose_name=_('locations'), blank=True
    )
    objects = EventManager()
    created_by = models.ForeignKey(
        auth_user_model, verbose_name=_("created by"), related_name='events', on_delete=models.CASCADE)
    categories = models.ManyToManyField(
        'Category', verbose_name=_('categories'), blank=True
    )

    def __init__(self, *args, **kwargs):
        super(Event, self).__init__(*args, **kwargs)
        self._last_popover_html = None
        self.title_extra = ''

    def get_l_start_date(self):
        """Localized start date."""
        return timezone.localtime(self.start_date)

    @cached_property
    def l_start_date(self):
        return self.get_l_start_date()

    def get_l_end_date(self):
        """Localized end date."""
        return timezone.localtime(self.end_date)

    @cached_property
    def l_end_date(self):
        return self.get_l_end_date()

    def is_happening(self, now):
        """Return True if the event is happening 'now', False if not."""
        start = self.l_start_date
        end = self.l_end_date
        happening = False
        # check that the event has started and 'now' is btwn start & end:
        if (now >= start) and (start.time() <= now.time() <= end.time()):
            if self.repeats('WEEKDAY'):
                if not now.weekday() > 4:  # must be weekday
                    happening = True
            elif self.repeats('DAILY') or self.repeats('NEVER'):
                happening = True
            elif self.repeats('MONTHLY'):
                if start.day <= now.day <= end.day:
                    happening = True
            elif self.repeats('YEARLY'):
                if (start.month <= now.month <= end.month) and \
                        (start.day <= now.day <= end.day):
                    happening = True
            else:
                repeat = {'WEEKLY': 7, 'BIWEEKLY': 14}
                while end <= now:
                    start += datetime.timedelta(days=repeat[self.repeat])
                    end += datetime.timedelta(days=repeat[self.repeat])
                if start <= now <= end:
                    happening = True
        return happening

    def repeats(self, repeat):
        return self.repeat == repeat

    def is_chunk(self):
        return self.l_start_date.day != self.l_end_date.day

    def starts_same_month_as(self, month):
        return self.l_start_date.month == month

    def ends_same_month_as(self, month):
        return self.l_end_date.month == month

    def starts_same_year_month_as(self, year, month):
        return self.l_start_date.year == year and \
               self.l_start_date.month == month

    def starts_same_month_not_year_as(self, month, year):
        return self.l_start_date.year != year and \
               self.l_start_date.month == month

    def starts_ends_same_month(self):
        return self.l_start_date.month == self.l_end_date.month

    def starts_ends_yr_mo(self, year, month):
        yr = self.l_start_date.year == year or self.l_end_date.year == year
        mo = self.l_start_date.month == month or self.l_end_date.month == month
        return yr and mo

    def get_start_end_diff(self):
        """Return the difference between start and end dates."""
        s = self.l_start_date
        e = self.l_end_date
        start = datetime.date(s.year, s.month, s.day)
        end = datetime.date(e.year, e.month, e.day)
        diff = start - end
        return abs(diff.days)

    @cached_property
    def start_end_diff(self):
        return self.get_start_end_diff()

    def clean(self):
        self.clean_start_end_dates()
        self.clean_repeat()

    def clean_start_end_dates(self):
        if self.start_date and self.end_date:
            if self.l_start_date > self.l_end_date:
                raise ValidationError(
                    "The event's start date must be before the end date."
                )
            elif (self.l_end_date - self.l_start_date) > datetime.timedelta(7):
                raise ValidationError(
                    "Only events spanning 7 days or less are supported."
                )

    def clean_repeat(self):
        if self.repeats('NEVER') and self.end_repeat:
            # events not scheduled to repeat should't have an end repeat date
            self.end_repeat = None

        if self.repeats('DAILY') or self.repeats('WEEKDAY'):
            if self.is_chunk():
                raise ValidationError(
                    "Repeating every day or every weekday is not supported \
                    for events that start and end on different days."
                )

    def get_absolute_url(self):
        return reverse('calendar:detail', args=[str(self.id)])

    class Meta:
        verbose_name = _('event')
        verbose_name_plural = _('events')


class Location(models.Model):
    name_location = models.CharField(_('Name'), max_length=255)
    region = models.CharField(
        _('Region'), max_length=63, blank=True)
    city = models.CharField(
        _('City / Town'), max_length=63, blank=True)
    country = models.CharField(_('Country'), max_length=127, blank=True)

    def __str__(self):
        return self.name_location


class Category(models.Model):
    title = models.CharField(_('title'), max_length=255)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name_plural = 'Categories'

events/views.py
from __future__ import unicode_literals

from django.shortcuts import render
from datetime import date, timedelta

# django:
from django.views.generic import ListView, DetailView
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.utils.dates import MONTHS_ALT

# thirdparties:
import six

# utils
from .models import Event
from events.utils.displays import month_display, day_display
from events.utils.mixins import JSONResponseMixin
from events.utils import common as c

CALENDAR_LOCALE = getattr(settings, 'CALENDAR_LOCALE', 'en_US.utf8')


class GenericEventView(JSONResponseMixin, ListView):
    model = Event

    def render_to_response(self, context, **kwargs):
        if self.request.is_ajax():
            return self.render_to_json_response(context, **kwargs)
        return super(GenericEventView, self).render_to_response(
            context, **kwargs
        )

    def get_context_data(self, **kwargs):
        context = super(GenericEventView, self).get_context_data(**kwargs)

        self.net, self.category, self.tag = c.get_net_category_tag(
            self.request
        )

        if self.category is not None:
            context['cal_category'] = self.category
        if self.tag is not None:
            context['cal_tag'] = self.tag
        return context


class EventMonthView(GenericEventView):
    template_name = 'event_month_list.html'

    def get_year_and_month(self, net, qs, **kwargs):
        """
        Get the year and month. First tries from kwargs, then from
        querystrings. If none, or if cal_ignore qs is specified,
        sets year and month to this year and this month.
        """
        now = c.get_now()
        year = now.year
        month = now.month + net
        month_orig = None

        if 'cal_ignore=true' not in qs:
            if 'year' and 'month' in self.kwargs:  # try kwargs
                year, month_orig = map(
                    int, (self.kwargs['year'], self.kwargs['month'])
                )
                month = month_orig + net
            else:
                try:  # try querystring
                    year = int(self.request.GET['cal_year'])
                    month_orig = int(self.request.GET['cal_month'])
                    month = month_orig + net
                except Exception:
                    pass
        # return the year and month, and any errors that may have occurred do
        # to an invalid month/year being given.
        return c.clean_year_month(year, month, month_orig)

    def get_month_events(self, *args, **kwargs):
        return Event.objects.all_month_events(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EventMonthView, self).get_context_data(**kwargs)

        qs = self.request.META['QUERY_STRING']

        year, month, error = self.get_year_and_month(self.net, qs)

        mini = True if 'cal_mini=true' in qs else False

        # get any querystrings that are not next/prev/year/month
        if qs:
            qs = c.get_qs(qs)

        # add a dict containing the year, month, and month name to the context
        current = dict(
            year=year, month_num=month, month=MONTHS_ALT[month][:3]
        )
        context['current'] = current

        display_month = MONTHS_ALT[month]

        if isinstance(display_month, six.binary_type):
            display_month = display_month.decode('utf-8')

        context['month_and_year'] = u"%(month)s, %(year)d" % (
            {'month': display_month, 'year': year}
        )

        if error:  # send any year/month errors
            context['cal_error'] = error

        # List enables sorting. As far as I can tell, .order_by() can't be used
        # here because we need it ordered by l_start_date.hour (simply ordering
        # by start_date won't work). The only alternative I've found is to use
        # extra(), but this would likely require different statements for
        # different databases...
        all_month_events = list(self.get_month_events(
            year, month, self.category, loc=True
        ))

        all_month_events.sort(key=lambda x: x.l_start_date.hour)

        start_day = getattr(settings, "CALENDAR_START_DAY", 0)
        context['calendar'] = month_display(
            year, month, all_month_events, start_day, self.net, qs, mini,
            request=self.request,
        )

        context['show_events'] = False
        if getattr(settings, "CALENDAR_SHOW_LIST", False):
            context['show_events'] = True
            context['events'] = c.order_events(all_month_events, d=True) \
                if self.request.is_ajax() else c.order_events(all_month_events)

        return context


class EventDayView(GenericEventView):
    template_name = 'event_day_list.html'

    def get_month_events(self, *args, **kwargs):
        return Event.objects.all_month_events(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(EventDayView, self).get_context_data(**kwargs)

        kw = self.kwargs
        y, m, d = map(int, (kw['year'], kw['month'], kw['day']))
        year, month, day, error = c.clean_year_month_day(y, m, d, self.net)

        if error:
            context['cal_error'] = error

        # Note that we don't prefetch 'cancellations' because they will be
        # prefetched later (in day_display in displays.py)
        all_month_events = self.get_month_events(
            year, month, self.category, self.tag
        )

        self.events = day_display(
            year, month, all_month_events, day
        )
        context['events'] = self.events

        display_month = MONTHS_ALT[month]
        if isinstance(display_month, six.binary_type):
            display_month = display_month.decode('utf-8')

        context['month'] = display_month
        context['month_num'] = month
        context['year'] = year
        context['day'] = day
        context['month_day_year'] = u"%(month)s %(day)d, %(year)d" % (
            {'month': display_month, 'day': day, 'year': year}
        )

        # for use in the template to build next & prev querystrings
        context['next'], context['prev'] = c.get_next_and_prev(self.net)
        return context


class EventDetailView(DetailView):
    model = Event
    context_object_name = 'event'

    def get_object(self):
        return get_object_or_404(
            Event.objects.prefetch_related(
                'location', 'categories'
            ),
            pk=self.kwargs['pk']
        )

events/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Medical Events{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/calendar.css' %}">
    {% block extra_css %}{% endblock extra_css %}
</head>
<body>
{% block content %}{% endblock content %}
<script src="{% static 'js/calendar.js' %}"></script>
{% block extra_js %}{% endblock extra_js %}
</body>
</html>

events/templates/event_day_list.html
{% extends 'middle.html' %}
{% load static i18n %}

{% block content %}

{% if cal_error %}
{{ cal_error }}
{% endif %}

<a href="">
    &larr; {% trans "Back to calendar" %}
</a>

<h1>
    {% trans "Events" %}<br>
    {% if cal_category and cal_tag %}
    {% blocktrans with c=cal_category %}
    in category <span id="cal-day-category">{{ c }}</span>
    {% endblocktrans %}
    {% elif cal_category %}
    {% blocktrans with c=cal_category %}
    with category <span id="cal-day-category">{{ c }}</span>
    {% endblocktrans %}
    {% endif %}
</h1>

<h2>{% trans "For" %}
    <span id="cal-day-mo">{{ month }}</span>
    <span id="cal-day-day">{{ day }}</span>,
    <span id="cal-day-year">{{ year }}</span>
</h2>
<a id="cal-day-prev" class="cal-day" href="{{ request.path }}?cal_prev={{ prev_qs }}">
    {% trans "Prev Day" %}
</a> |
<a id="cal-day-next" class="cal-day" href="{{ request.path }}?cal_next={{ next_qs}}">
    {% trans "Next Day" %}
</a>

<ul class="day-event-list">
    {% for event in events %}
    <li>{{ event.title }}</li>
    {% empty %}
    {% trans "Oops.. No events!" %}
    {% endfor %}
</ul>

{% endblock content %}

events/templates/event_detail.html
{% extends 'middle.html' %}
{% load static i18n %}

{% block content %}
<h1>{{ event.title }}</h1>
<p>{{ event.description }}</p>


{% if event.start_end_diff %}
<b>{% blocktrans with event_duration_days=event.start_end_diff %}This is a {{ event_duration_days }} day event.{%
    endblocktrans %}</b><br>
{% endif %}

{% if next_event %}
<b>{% blocktrans with repeat_lower=repeat|lower %}This event repeats {{ repeat_lower }}.{% endblocktrans %}</b>
<p>
    {{ _("Next event date:") }}
    {{ next_event|date:"SHORT_DATE_FORMAT" }}
    {{ event.start_date|time }} -
    {{ event.end_date|time }}{% if next_or_prev %}{% endif %}
    {% elif last_event %}
    <b>{% blocktrans with repeat_lower=repeat|lower %}This was an event that repeated {{ repeat_lower }}.{%
        endblocktrans %}</b>
<p>{% blocktrans with last_event_date=last_event|date:"SHORT_DATE_FORMAT" %}The last event was on {{ last_event_date
    }}{% endblocktrans %}{% if next_or_prev %} {% endif %}
    {% else %}
<p>{{ _("When:") }}
    {% if event_days %}
<ul>
    {% for e in event_days %}
    <li>
        {% blocktrans with num_day=forloop.counter %}Day {{ num_day }}{% endblocktrans %}: {{ e|date:"SHORT_DATE_FORMAT"
        }} - {{ event.end_date|time }}

    </li>
    {% endfor %}
    {% endfor %}
</ul>
{% else %}
{{ event.start_date|date:"SHORT_DATE_FORMAT" }} - {{ event.end_date|time }}

{% endif %}
{% endif %}

({{ _("today is:") }} {% now "SHORT_DATE_FORMAT" %})
</p>


{% if event.location.all %}
<p>{% blocktrans count counter=event.location.all.count %}Location:{% plural %}Locations:{% endblocktrans %}<br>
    {% for l in event.location.all %}
    {{ l.name }}<br>
    {% if l.city %}{{ l.city }},{% endif %}
    {% if l.state %}{{ l.state }}{% endif %}
    {% if l.country %}{{ l.country }}<br>{% endif %}
    {% endfor %}
</p>
{% endif %}


{% if event.categories.all %}
{% blocktrans count counter=event.categories.all.count %}Category:{% plural %}Categories:{% endblocktrans %}
<ul>
    {% for category in event.categories.all %}
    <li>{{ category.title }}</li>
    {% endfor %}
</ul>
{% endif %}


{% endblock content %}

events/templates/event_month_list.html
{% extends 'middle.html' %}
{% load static happenings_tags %}
{% block content %}

{% if cal_error %}
{{ cal_error }}
{% endif %}

{% if not show_events %}<h1>Medical Events</h1>{% endif %}

<div id="event-calendar">
    {{ calendar|safe }}
</div>

{% if show_events %}
<h1 id="month-list-events-title">
    {% if cal_category and cal_tag %}
    Events in category {{ cal_category }}
    with tag = {{ cal_tag }}
    {% elif cal_category %}
    Events in {{ cal_category }}
    {% elif cal_tag %}
    Events with tag = {{ cal_tag }}
    {% else %}
    Events
    {% endif %}
</h1>

<h3>For <span id="month-and-year">{{ month_and_year }}</span></h3>
{% include 'partials/event_list.html' %}
{% endif %}

{% endblock content %}

events/templates/middle.html
{% extends 'base.html' %}